# Application
app:
  sse:
    heartbeat:
      enabled: true
      interval: 10s
    cleanup-period: 10m
# Spring
spring:
  application:
    name: fibonacci-java-web
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/fibonacci
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: fibonacci-java-spring-hikari
      maximum-pool-size: 10
      connection-test-query: "SELECT 1"
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true
    validate-on-migrate: true
    clean-disabled: true
    output-query-results: true
    user: postgres
    password: postgres
    locations:
      - filesystem:java/flyway/{vendor}
      # Test location
      - filesystem:../../java/flyway/{vendor}
    postgresql:
      transactional-lock: true
  docker:
    compose:
      skip:
        in-tests: true
      enabled: false
      lifecycle-management: start_only
      file: ${user.dir}/java/docker-compose-dev.yaml
# Server
server:
  http2:
    enabled: true
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
# Logging
logging:
  level:
    root: INFO
    com.github.mangila.fibonacci.scheduler.config: INFO
    com.github.mangila.fibonacci.scheduler.controller: INFO
    com.github.mangila.fibonacci.scheduler.repository: INFO
    com.github.mangila.fibonacci.scheduler.scheduler: INFO
    com.github.mangila.fibonacci.scheduler.task: INFO