app:
  flush:
    enabled: false
  sse:
    heartbeat:
      enabled: true
      interval: 10s
    cleanup-period: 10m
# Spring Properties
spring:
  flyway:
    clean-disabled: false
  docker:
    compose:
      enabled: true
      stop:
        command: down
      file: ${user.dir}/java/docker-compose-dev.yaml
# Logging
logging:
  level:
    root: INFO
    com.github.mangila.fibonacci.scheduler.config: INFO
    com.github.mangila.fibonacci.scheduler.controller: INFO
    com.github.mangila.fibonacci.scheduler.repository: INFO
    com.github.mangila.fibonacci.scheduler.scheduler: INFO
    com.github.mangila.fibonacci.scheduler.task: INFO
# Server
server:
  port: 8080
# SpringDoc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: true
  cache:
    disabled: true
