# Application
app:
  flush:
    enabled: false
  pg-listen:
    enabled: false
    channel: "fibonacci"
  sse:
    enabled: false
    heartbeat:
      enabled: false
      interval: 10s
    cleanup-period: 10m
# Spring
spring:
  application:
    name: fibonacci-java-web
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/fibonacci
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: fibonacci-java-spring-hikari
      maximum-pool-size: 10
      connection-test-query: "SELECT 1"
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true
    validate-on-migrate: true
    clean-disabled: true
    output-query-results: true
    fail-on-missing-locations: true
    locations:
      - classpath:db/migration
    postgresql:
      transactional-lock: true
  docker:
    compose:
      skip:
        in-tests: true
      enabled: false
      file: ${user.dir}/java/docker-compose-dev.yaml
      stop:
        command: down
jobrunr:
  dashboard:
    enabled: true
  background-job-server:
    enabled: false
  job-scheduler:
    enabled: false
  database:
    table-prefix: fibonacci_
# Server
server:
  http2:
    enabled: true
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
# Logging
logging:
  level:
    root: INFO
    com.github.mangila.fibonacci.web.sse: INFO
    com.github.mangila.fibonacci.web.ws: INFO
# SpringDoc
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  show-actuator: false
  cache:
    disabled: false