# Spring
spring:
  application:
    name: fibonacci-java-spring
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/fibonacci?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: fibonacci-java-spring-hikari
      maximum-pool-size: 10
  sql:
    init:
      mode: always
  docker:
    compose:
      skip:
        in-tests: true
  # Logging
  #logging:
  #  level:
  #   org.springframework.jdbc.core.JdbcTemplate: DEBUG