# Application
app:
  fibonacci:
    algorithm: fast_doubling
    offset: 1
    limit: 1000
    delay: 2s
# Spring
spring:
  application:
    name: fibonacci-java-spring
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://localhost:5432/fibonacci
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: fibonacci-java-spring-hikari
      maximum-pool-size: 10
  sql:
    init:
      mode: always
      encoding: UTF-8
      separator: ^^
  docker:
    compose:
      skip:
        in-tests: true
      lifecycle-management: start_only
# Server
server:
  port: 8080
  http2:
    enabled: true