services:
  postgres-dev:
    image: postgres:18-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_DB: fibonacci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-bloom-and-insight
    ports:
      - "6379:6379"  # Redis Protocol
      - "8001:8001"  # Redis Insight Web UI
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
