services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: fibonacci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - fibonacci-net
  web:
    image: fibonacci-java-web:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fibonacci
      APP_PG-LISTEN_ENABLED: "true"
      APP_SSE_ENABLED: "true"
      APP_SSE_HEARTBEAT_ENABLED: "true"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - fibonacci-net
  jobrunr:
    image: fibonacci-java-jobrunr:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fibonacci
      APP_JOB_PRODUCER_ENABLED: "true"
      APP_JOB_CONSUMER_ENABLED: "true"
    depends_on:
      - postgres
    networks:
      - fibonacci-net
networks:
  fibonacci-net:
