services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: fibonacci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - fibonacci-net
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"  # Redis Protocol
      - "8001:8001"  # Redis Insight Web UI
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - fibonacci-net
  web:
    image: fibonacci-java-web:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fibonacci
      SPRING_DATA_REDIS_HOST: redis-stack
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis-stack
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - fibonacci-net
networks:
  fibonacci-net:
