services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: fibonacci
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - fibonacci-net
  web:
    image: fibonacci-java-web:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fibonacci
      SPRING_FLYWAY_LOCATIONS: filesystem:/flyway/{vendor}
      SPRING_FLYWAY_FAIL_ON_MISSING_LOCATIONS: true
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - fibonacci-net
  scheduler:
    image: fibonacci-java-scheduler:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fibonacci
      SPRING_FLYWAY_LOCATIONS: filesystem:/flyway/{vendor}
      SPRING_FLYWAY_FAIL_ON_MISSING_LOCATIONS: true
    depends_on:
      - postgres
      - web
    ports:
      # Scheduler API
      - "8081:8080"
      # JobRunr Dashboard
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - fibonacci-net
networks:
  fibonacci-net:
