# Spring
spring:
  application:
    name: fibonacci-java-scheduler
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fibonacci
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: fibonacci-java-spring-hikari
      maximum-pool-size: 10
      connection-test-query: "SELECT 1"
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true
    validate-on-migrate: true
    clean-disabled: true
    output-query-results: true
    user: postgres
    password: postgres
    locations:
      - filesystem:java/flyway/{vendor}
      # Test location
      - filesystem:../../java/flyway/{vendor}
    postgresql:
      transactional-lock: true
  docker:
    compose:
      skip:
        in-tests: true
      enabled: false
      lifecycle-management: start-and-stop
      file: ${user.dir}/java/docker-compose-dev.yaml
# JobRunr
jobrunr:
  dashboard:
    enabled: true
  job-scheduler:
    enabled: true
  background-job-server:
    thread-type: virtualthreads
    enabled: true
    poll-interval-in-seconds: 15
    name: fibonacci-java-scheduler
    worker-count: 1
  database:
    skip-create: false
    table-prefix: fibonacci_
# Server
server:
  http2:
    enabled: true
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
# Logging
logging:
  level:
    root: INFO
    com.github.mangila.fibonacci.scheduler.config: INFO
    com.github.mangila.fibonacci.scheduler.controller: INFO
    com.github.mangila.fibonacci.scheduler.repository: INFO
    com.github.mangila.fibonacci.scheduler.scheduler: INFO
    com.github.mangila.fibonacci.scheduler.task: INFO