# Application
app:
  flush:
    enabled: true
  job:
    producer:
      enabled: true
      limit: 1_000
      algorithm: iterative
    consumer:
      enabled: true
      limit: 50
      cron: "0/45 * * * * *"
# Spring Properties
spring:
  flyway:
    clean-disabled: false
  docker:
    compose:
      enabled: true
      stop:
        command: down
      file: ${user.dir}/java/docker-compose-dev.yaml
# Logging
logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    com.github.mangila.fibonacci.jobrunr.config: INFO
    com.github.mangila.fibonacci.jobrunr.job: INFO
    com.github.mangila.fibonacci.jobrunr.job.consumer: INFO
    com.github.mangila.fibonacci.jobrunr.job.producer: DEBUG