# Application
app:
  job:
    producer:
      enabled: false
      limit: 200
      algorithm: iterative
      cron: "0 0/1 * * * *"
    consumer:
      enabled: false
      limit: 50
      cron: "0 0/1 * * * *"
    zset:
      drain:
        enabled: false
        limit: 50
        cron: "0 0/1 * * * *"
      insert:
        enabled: false
        limit: 50
        cron: "0 0/1 * * * *"
# Spring
spring:
  application:
    name: fibonacci-java-jobrunr
  main:
    web-application-type: none
    keep-alive: true
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fibonacci?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ${spring.application.name}
      maximum-pool-size: 10
      connection-test-query: "SELECT 1"
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-migration-naming: true
    validate-on-migrate: true
    clean-disabled: true
    output-query-results: true
    fail-on-missing-locations: true
    locations:
      - classpath:db/migration
    postgresql:
      transactional-lock: true
  docker:
    compose:
      skip:
        in-tests: true
      enabled: false
      file: ${user.dir}/java/docker-compose-dev.yaml
  data:
    redis:
      host: localhost
      port: 6379
      client-name: ${spring.application.name}
      jedis:
        pool:
          enabled: true
# JobRunr
jobrunr:
  job-scheduler:
    enabled: true
  background-job-server:
    thread-type: virtualthreads
    enabled: true
    poll-interval-in-seconds: 15
    name: ${spring.application.name}
    delete-succeeded-jobs-after: 36h
    permanently-delete-deleted-jobs-after: 72h
    succeeded-jobs-request-size: 5000
  database:
    skip-create: false
    table-prefix: fibonacci_
# Logging
logging:
  level:
    root: INFO
    com.github.mangila.fibonacci.jobrunr.config: INFO
    com.github.mangila.fibonacci.jobrunr.job: INFO
    com.github.mangila.fibonacci.jobrunr.model: INFO
    com.github.mangila.fibonacci.jobrunr.scheduler: INFO
    com.github.mangila.fibonacci.jobrunr.task: INFO