# Spring Properties
spring:
  flyway:
    clean-disabled: false
  docker:
    compose:
      enabled: true
      stop:
        command: down
      file: ${user.dir}/java/docker-compose-dev.yaml
# Logging
logging:
  level:
    root: INFO
    com.github.mangila.fibonacci.jobrunr.config: INFO
    com.github.mangila.fibonacci.jobrunr.job: INFO
    com.github.mangila.fibonacci.jobrunr.model: INFO
    com.github.mangila.fibonacci.jobrunr.scheduler: INFO
    com.github.mangila.fibonacci.jobrunr.task: INFO